language: ruby
rvm:
- 2.3.1
services:
- postgresql
addons:
  postgresql: '9.3'
before_script:
- cp config/database.travis.yml config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
